### ISSUE TITLE
Collision is not necessary 

### ISSUE THREAD

**Issue by Esnos33** [godotrecipes/2d_grid_movement#2]
Hi, I just checked, and If I delete collision from player, everything is working the same way as before. Is this intended?

**Comment by cbscribe** [comment]
The player's collision is not used for movement, but you may want a collision on your player for other aspects of your game. Plus since we're using an `Area2D` for the player in this demo, it needs a collision.

Depending on your needs, you'd be perfectly fine using a `Sprite2D` as the root node and just using the raycast for move detection.
